# src/report/i18n.py
"""Internationalization strings for PDF reports."""

STRINGS = {
    "en": {
        # Daily report
        "daily_title": "AI Practice Daily",
        "daily_header": "AI Practice Daily — AIteller",
        "daily_filename": "AI_Practice_Daily_{date}.pdf",
        "daily_stats": "{total} items  |  {sources} sources  |  {highlights} highlights",
        "daily_source_prefix": "Sources: ",
        "daily_source_unit": "",
        "daily_footer_1": "Content automatically collected, scored and summarized by AIteller.",
        "daily_footer_2": "Sources include Hacker News, Reddit, GitHub, arXiv, YouTube, Bilibili, etc.",
        "daily_footer_3": "Please refer to the original links for accuracy.",

        # Weekly report
        "weekly_title": "AI Practice Weekly",
        "weekly_header": "AI Practice Weekly",
        "weekly_filename": "AI_Practice_Weekly_{start}_{end}.pdf",
        "weekly_subtitle": "{start} ~ {end} | {count} curated items",
        "weekly_source_overview": "Source Overview",
        "weekly_source_headers": ["Source", "Count", "Avg"],
        "weekly_source_headers_full": ["Source", "Crawled", "Passed", "Avg"],
        "weekly_notes_title": "Notes",
        "weekly_notes_body": (
            "This report uses a tiered category system with a 0-10 scoring scale. "
            "Content is organized in a dense two-column layout, sorted by Tier > Category > Score "
            "for quick scanning."
        ),
        "weekly_category_dist": "Category Distribution",
        "weekly_category_header": "Category",
        "weekly_total": "Total",
        "weekly_novelty_note": "Note: Novelty/creative experiments ({count}) are in a separate section, not mixed into core engineering categories.",
        "weekly_items_unit": "",
        "weekly_other": "Other",

        # Tier labels
        "tier_daily": {
            5: ("Must Read", (220, 53, 69)),
            4: ("Featured", (255, 152, 0)),
            3: ("Recommended", (76, 175, 80)),
            2: ("Reference", (158, 158, 158)),
        },
        "tier_weekly": {
            1: ("Tier 1 · Practice", (183, 28, 28), (254, 242, 242)),
            2: ("Tier 2 · Deep Tech", (194, 65, 12), (255, 247, 237)),
            3: ("Tier 3 · Big Picture", (30, 64, 175), (239, 246, 255)),
            0: ("Novelty / Experiments", (71, 85, 105), (248, 250, 252)),
        },

        # Source display names
        "sources": {
            "hackernews": "Hacker News",
            "reddit": "Reddit",
            "github_trending": "GitHub Trending",
            "arxiv": "arXiv",
            "youtube": "YouTube",
            "bilibili": "Bilibili",
            "twitter": "Twitter/X",
            "rss_blogs": "Tech Blogs",
            "hf_papers": "HF Papers",
            "devto": "Dev.to",
            "medium": "Medium",
            "lobsters": "Lobsters",
        },
        "source_alias": {
            "hackernews": "HN",
            "reddit": "Reddit",
            "github_trending": "GitHub",
            "arxiv": "arXiv",
            "youtube": "YT",
            "bilibili": "Bili",
            "twitter": "X",
            "rss_blogs": "Blogs",
            "hf_papers": "HF",
        },

        # Metadata labels
        "author": "by",
        "views": "views",
        "likes": "likes",
        "no_title": "Untitled",

        # Common
        "page_footer": "Page {page}  |  Generated by AIteller",
        "section_count": "{label} ({count})",
        "font_error": "No CJK fonts found. Please install SimHei or Microsoft YaHei.",
    },

    "zh": {
        "daily_title": "AI 实践日报",
        "daily_header": "AI 实践日报 — AIteller",
        "daily_filename": "AI实践日报_{date}.pdf",
        "daily_stats": "共收录 {total} 篇内容  |  {sources} 个来源  |  {highlights} 篇精选",
        "daily_source_prefix": "来源：",
        "daily_source_unit": "篇",
        "daily_footer_1": "以上内容由 AIteller 自动收集、评分和摘要生成。",
        "daily_footer_2": "信息来源包括 Hacker News、Reddit、GitHub、arXiv、YouTube、B站 等。",
        "daily_footer_3": "如有疑问请以原文链接为准。",

        "weekly_title": "AI 实践周报",
        "weekly_header": "AI 实践周报",
        "weekly_filename": "AI实践周报_{start}_{end}.pdf",
        "weekly_subtitle": "{start} ~ {end} | 共 {count} 篇精选",
        "weekly_source_overview": "来源概览",
        "weekly_source_headers": ["来源", "数量", "均分"],
        "weekly_source_headers_full": ["来源", "爬取", "入选", "均分"],
        "weekly_notes_title": "说明",
        "weekly_notes_body": (
            "本报告沿用 experiment_results 的分类体系，保留 5.x / 6.x 十分制分数。"
            "正文采用对称双栏高密度列表，按 Tier → 分类 → 分数排序，便于快速扫读。"
        ),
        "weekly_category_dist": "分类分布",
        "weekly_category_header": "分类",
        "weekly_total": "总计",
        "weekly_novelty_note": "注：花边/创意实验 {count} 条，已移到正文单独板块，不混入核心工程分类表。",
        "weekly_items_unit": "篇",
        "weekly_other": "其他",

        "tier_daily": {
            5: ("必读", (220, 53, 69)),
            4: ("精选", (255, 152, 0)),
            3: ("推荐", (76, 175, 80)),
            2: ("参考", (158, 158, 158)),
        },
        "tier_weekly": {
            1: ("Tier 1 · 实践经验", (183, 28, 28), (254, 242, 242)),
            2: ("Tier 2 · 技术深度", (194, 65, 12), (255, 247, 237)),
            3: ("Tier 3 · 宏观视野", (30, 64, 175), (239, 246, 255)),
            0: ("花边 / 创意实验", (71, 85, 105), (248, 250, 252)),
        },

        "sources": {
            "hackernews": "Hacker News",
            "reddit": "Reddit",
            "github_trending": "GitHub 趋势",
            "arxiv": "arXiv 论文",
            "youtube": "YouTube",
            "bilibili": "B站",
            "twitter": "Twitter/X",
            "rss_blogs": "技术博客",
            "hf_papers": "HF Papers",
            "devto": "Dev.to",
            "medium": "Medium",
            "lobsters": "Lobsters",
        },
        "source_alias": {
            "hackernews": "HN",
            "reddit": "Reddit",
            "github_trending": "GitHub",
            "arxiv": "arXiv",
            "youtube": "YT",
            "bilibili": "B站",
            "twitter": "X",
            "rss_blogs": "博客",
            "hf_papers": "HF",
        },

        "author": "作者:",
        "views": "浏览",
        "likes": "点赞",
        "no_title": "无标题",

        "page_footer": "第 {page} 页  |  由 AIteller 自动生成",
        "section_count": "{label}（{count}{unit}）",
        "font_error": "未找到中文字体。请确保系统安装了 SimHei 或 Microsoft YaHei 字体。",
    },
}


# Category names in both languages
CATEGORY_NAMES = {
    "en": {
        "enterprise_arch": "Enterprise Architecture",
        "personal_exp": "Personal Experience",
        "personal_workflow": "Workflows",
        "postmortem": "Postmortems",
        "tool_comparison": "Tool Comparisons",
        "prompt_agent": "Prompt/Agent Engineering",
        "deploy_finetune": "Deploy/Fine-tuning",
        "rag_retrieval": "RAG/Retrieval",
        "ai_vertical": "AI + Industry",
        "opensource_tool": "Open Source Tools",
        "team_process": "Team Process",
        "novelty": "Novelty/Experiments",
    },
    "zh": {
        "enterprise_arch": "公司架构层面",
        "personal_exp": "个人使用经验",
        "personal_workflow": "个人实践工作流",
        "postmortem": "故障/踩坑复盘",
        "tool_comparison": "工具对比评测",
        "prompt_agent": "Prompt/Agent 工程",
        "deploy_finetune": "模型部署/微调",
        "rag_retrieval": "RAG/检索系统",
        "ai_vertical": "AI+垂直行业",
        "opensource_tool": "开源项目/工具",
        "team_process": "团队协作/流程",
        "novelty": "花边/创意实验",
    },
}


def get_strings(lang: str = "en") -> dict:
    return STRINGS.get(lang, STRINGS["en"])


def get_category_name(category_id: str, lang: str = "en") -> str:
    return CATEGORY_NAMES.get(lang, CATEGORY_NAMES["en"]).get(category_id, category_id)
